### ISSUE TITLE
Potential for race condition when accessing `listeners` dictionary?

### ISSUE THREAD

**Issue by Ben-G** [linkedin/ConsistencyManager-iOS#1]
Thanks for sharing this! It's certainly an interesting idea.

Looking over the code it appears that the `listener` dictionary is being accessed both from the `mainQueue` and the libraries `dispatchQueue`. 

Since Swift properties & data structures are not thread safe I see a potential cause for race conditions - or am I missing something?

Thanks again for sharing!

**Comment by nicksnyder** [comment]
@Ben-G Can you be more specific with a file and line number?

**Comment by plivesey** [comment]
You're not missing anything listeners and pausedListeners are not thread-safe.
listeners - should only be accessed on dispatchQueue
pausedListeners - should only be accessed on the main thread

You may be looking at line 490, which looks like it's using listeners on the main thread, but actually, its a local variable which hides the ivar? Not great naming here...

**Comment by Ben-G** [comment]
Thanks for clarifying @plivesey. I indeed got tricked by line 490. I guess implicit self can be an issue when just skimming code on GitHub 😉

Thanks for answering my general question around concurrency, makes sense!
