### ISSUE TITLE
Swift 3 migration

### ISSUE THREAD

**Issue by RishabhTayal** [linkedin/ConsistencyManager-iOS#26]
Implemented in PR #25

**Comment by RishabhTayal** [comment]
PR: #27

**Comment by plivesey** [comment]
Created #29 to track test problems. So feel like you can close this?

**Comment by RishabhTayal** [comment]
Not sure.

**Comment by plivesey** [comment]
Why don't we keep this open until it's merged into master.

**Comment by plivesey** [comment]
For others representing this ticket, see swift3 branch.

**Comment by RishabhTayal** [comment]
That's fine.

**Comment by plivesey** [comment]
#36 Does all the work for the library. Now just need sample app.

**Comment by plivesey** [comment]
#37 completes this issue
