### ISSUE TITLE
Current master commit does not build

### ISSUE THREAD

**Issue by dolfs** [linkedin/ConsistencyManager-iOS#42]
I am attempting to use this, with RocketData, in a Swift 3 based project with Xcode 8. I am referring my cart file to the master branch to get the latest (for now). My project is an iOS project, setup for universal and configured to run on the simulator.

When running `carthage update` I get this:

> `*** Checking out ConsistencyManager-iOS at "5ed13ecc9d3492dc08ce6c6787d705ea708ee226"
> *** Building scheme "ConsistencyManager" in ConsistencyManager.xcodeproj
> Failed to write to /Users/aname/Documents/Project/Carthage/Build/Mac/ConsistencyManager.framework: Error Domain=NSCocoaErrorDomain Code=260 "The file “ConsistencyManager.framework” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/aname/Library/Developer/Xcode/DerivedData/ConsistencyManager-fearqdlqpzasxjgmoxazbykbsxxj/Build/Products/Release-iphoneos/ConsistencyManager.framework, NSUnderlyingError=0x7fc8bc70a9c0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
> `

Notice that the error is about a build for Mac (it refers to Carthage/Build/Mac), whereas I only need a build for iOS. I can get around that with `--platform iOS`, but IMHO this error should not happen.

**Comment by plivesey** [comment]
Yes, I agree. This was reported yesterday, so I'm taking a look. Carthage is running the wrong xcodebuild commands.

I'm not very familiar with Carthage. I'm trying to work out if there's a way to tell Carthage which commands to run. I don't really understand how it generates the build commands currently.

**Comment by plivesey** [comment]
https://github.com/Carthage/Carthage/issues/1547
