### ISSUE TITLE
Rename project to ConsistencyManager

### ISSUE THREAD

**Issue by plivesey** [linkedin/ConsistencyManager-iOS#50]
`-iOS` is wrong now since it handles tvOS and macOS. The pod is also called `ConsistencyManager`. This shouldn't be a problem because there are no other big projects with this name.

**Comment by hebertialmeida** [comment]
How about this? Now supports macOS, tvOS, iOS...

**Comment by plivesey** [comment]
:/ I'm worried about breaking people's carthage and cocoapods when they're pointing to the github directly. Do you know if it's possible to rename but also have the old url redirect?

**Comment by hebertialmeida** [comment]
I found this: https://github.blog/2013-05-16-repository-redirects-are-here/

So, it seems that Github handles that for us.

**Comment by plivesey** [comment]
Oh, awesome. I'm down then. I can take care of renaming the repo. Anything else that needs to be done?

**Comment by hebertialmeida** [comment]
If you rename I can open a PR to fix the references to the old one

**Comment by plivesey** [comment]
Cool. Should get to this later today/tomorrow. I want to test it as I do it to double check.

**Comment by plivesey** [comment]
Done and tested. Thanks for the research.
