### ISSUE TITLE
collections

### ISSUE THREAD

**Issue by eyalc** [linkedin/ConsistencyManager-iOS#52]
can u please give an example for use with collections?
I have a view controller that holds an array of `Person` objects and`Person` confirm to the `ConsistencyManagerModel` protocol.
Now how can i get updates when one of them changes?
I looked at the docs and the sample app, it seems that the sample app uses a parent model for that, but i prefer not to do it.
I also read about the BatchListener but i didn't understand how to use it.
thanks

**Comment by plivesey** [comment]
First of all, have you checked out Rocket Data (https://github.com/linkedin/RocketData). The collection data provider there does this automatically, so it's something I'd consider using (even if you don't use the caching logic yet).

But anyway, if you're using consistency manager directly you can do something like:

```
class MyClass {
    var people: [Person]

    func listenToChanges() {
        ConsistencyManager.shared.addListener(self)
    }

    func currentModel() -> ConsistencyManagerModel? {
        let model = BatchUpdateModel(models: people)
        return model
    }

    func modelUpdated(_ model: ConsistencyManagerModel?, updates: ModelUpdates, context: Any?) {
        if let model = model as? BatchUpdateModel {
            self.people = model.models.flatMap { $0 }
        } else {
            assertFailure("wrong class")
        }
    }
}
```

If you want, you can also assign an ID to this batch model which means that you can sync this collection across different view controllers (i.e. get deletes/inserts/etc) which is how RocketData does this.

**Comment by eyalc** [comment]
@plivesey thank you that was very helpful!

just another issue im trying to understand.
suppose my `Person` model has a (Array) property called `phones: [Phone]`
now suppose one of the phone objects in that array changed, should I expect to get a callback `modelUpdated` on the Person listener? 
Because i tried it and i didnt get the update, im not sure if im doing something wrong or if this framwork doesnt support this feature. (get callback to the parent if his child get changed)

**Comment by plivesey** [comment]
Yes, this should definitely work. A few things to check:
1) Do the phone objects have an model identifier
2) In the `forEach` in the Person model are you iterating over the phone models? And in the `map` function do you replace the phone objects?

**Comment by plivesey** [comment]
Closing this issue because it's a year old now and looks resolved
