### ISSUE TITLE
Swift 4 Support

### ISSUE THREAD

**Issue by NinoScript** [linkedin/ConsistencyManager-iOS#53]
Beware, this project compiles without errors as Swift 4, but crashes at runtime because of missing `@objc` in methods like `applicationDidReceiveMemoryWarning`.

Running the migrator would probably fix this.

BTW, this is not actually this library's fault as it is explicit in the readme that it's a Swift 3 library, but rather a symptom of CocoaPods/CocoaPods#7134.

**Comment by NinoScript** [comment]
Actually, at second glance, the only part of the code that needs `@objc` is this line:
https://github.com/linkedin/ConsistencyManager-iOS/blob/a93c001efe76975a628c74559edc434bbceeef7f/ConsistencyManager/ConsistencyManager.swift#L847

That also means that the `MemoryWarningListener` class doesn't require being an NSObject subclass, and because that seems to be the only reason for its existence, it could be deleted and just prepend `@objc` to `ConsistencyManager.applicationDidReceiveMemoryWarning(_:)` instead.

**Comment by NinoScript** [comment]
Oh, and I just realized that this compiles in Swift 4 because of this line:
https://github.com/linkedin/ConsistencyManager-iOS/blob/a93c001efe76975a628c74559edc434bbceeef7f/ConsistencyManager/ConsistencyManager.swift#L839

This part `UIApplicationDelegate.applicationDidReceiveMemoryWarning(_:)` confuses the compiler, because that method is indeed accesible by Objective-C, while `self.applicationDidReceiveMemoryWarning(_:)` is not.

**Comment by plivesey** [comment]
@vargon is this now fixed? Can we close this?

**Comment by vargon** [comment]
Yep. Thanks!
