### ISSUE TITLE
Push the release 5.1.2 to cocoapods repo

### ISSUE THREAD

**Issue by hebertialmeida** [linkedin/ConsistencyManager-iOS#58]
Could you please push the release 5.1.2 to Cocoapods repo? I cant updated it on https://github.com/linkedin/RocketData/ podspec file because the latest version there is `5.0.0`

https://cocoapods.org/pods/ConsistencyManager

Thank you!!

**Comment by plivesey** [comment]
I believe the LinkedIn team are going to get to this soon...sorry for the delay.

**Comment by hebertialmeida** [comment]
@plivesey Thanks! Do they have access to push this to Cocoapods? Seems that you are the maintainer there.

**Comment by plivesey** [comment]
@hebertialmeida I'm very sorry for the delay with this. I now have full push/commit/approve writes for the repo and will be maintaining the repo going forward.

I've actually updated the pod to 5.2.0 and pushed that to the cocoapod repo. I just tested it with `pod update`. Lmk if you have any problems. Going to work on the `RocketData` repo later today.

**Comment by hebertialmeida** [comment]
Good news! Alright I will try that today...
