### ISSUE TITLE
2.0.0 Release

### ISSUE THREAD

**Issue by plivesey** [linkedin/ConsistencyManager-iOS#6]
We are in the middle of adding support for projections which will likely require a major bump of the library. This will allow people the ability to have different classes with the same ID.

If anyone has any other feature requests, we should probably include them in this release.

Current list:
- [x] Add support for projections
- [x] Ensure pausing, batching and other features also work with projections
- [x] Add unit tests to all features for projections
- [x] Add ability to clear the consistency manager (cancel all tasks and wipe listeners)
- [x] Add docs for projections

**Comment by plivesey** [comment]
@oliverhu wants to add the ability to clear the consistency manager. This is useful when logging out or when running UI Tests (being able to ensure nothing gets changed during the next test unexpectedly).

It'd be a new API, but involves changing a bunch of things like changing from a `dispatch_queue` to an `NSOperationQueue`.

Adding it to the list.

**Comment by nicksnyder** [comment]
@plivesey I would recommend creating a separate issue for each feature/request and then tagging each with the 2.0.0 milestone. This enables you to track and discuss each independently.

**Comment by plivesey** [comment]
👍

**Comment by plivesey** [comment]
Finished all tasks for 2.0.0.

**Comment by plivesey** [comment]
Currently, running integration tests with the new consistency manager on the LinkedIn flagship app. If those pass, gives high confidence that this build is ready to go and I'll merge and release.

**Comment by plivesey** [comment]
Tests passed. Now, just need to release and push the docs.

**Comment by plivesey** [comment]
#24 is the merge into master
